# namespace: coldworld

# coldbridge Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldbridge
  namespace: coldworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coldbridge
  template:
    metadata:
      labels:
        app: coldbridge
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      containers:
      - name: coldbridge
        image: coldbridge
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: rtspservice
      
---

# coldbridge Service
apiVersion: v1
kind: Service
metadata:
  name: coldbridge-service
  namespace: coldworld
spec:
  type: NodePort
  selector:
    app: coldbridge
  ports:
  - protocol: TCP
    targetPort: rtspservice
    port: 8888
    nodePort: 8888

---

# coldmountain Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldmountain
  namespace: coldworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coldmountain
  template:
    metadata:
      labels:
        app: coldmountain
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      containers:
      - name: coldmountain
        image: coldmountain:201016.03
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8899
          name: apiservice

---

# coldmountain Service
apiVersion: v1
kind: Service
metadata:
  name: coldmountain-service
  namespace: coldworld
spec:
  type: NodePort
  selector:
    app: coldmountain
  ports:
  - protocol: TCP
    targetPort: apiservice
    port: 8899
    nodePort: 8899

---

# coldcloud Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldcloud
  namespace: coldworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coldcloud
  template:
    metadata:
      labels:
        app: coldcloud
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      containers:
      - name: coldcloud
        image: coldcloud:201020.01
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: webservice

---

# coldcloud Service
apiVersion: v1
kind: Service
metadata:
  name: coldcloud-service
  namespace: coldworld
spec:
  type: NodePort
  selector:
    app: coldcloud
  ports:
  - protocol: TCP
    targetPort: webservice
    port: 8089
    nodePort: 8089

---

# coldrepo Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldrepo
  namespace: coldworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coldrepo
  template:
    metadata:
      labels:
        app: coldrepo
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      containers:
      - name: coldrepo
        image: coldrepo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysqlservice

---

# coldrepo Service
apiVersion: v1
kind: Service
metadata:
  name: coldrepo-service
  namespace: coldworld
spec:
  type: NodePort
  selector:
    app: coldrepo
  ports:
  - protocol: TCP
    targetPort: mysqlservice
    port: 3306
    nodePort: 3306